import { useState } from "react";

const AIReplyGenerator = () => {
  const [prompt, setPrompt] = useState("");
  const [tone, setTone] = useState("professional");
  const [loading, setLoading] = useState(false);
  const [generatedReply, setGeneratedReply] = useState("");

  const tones = [
    { value: "professional", label: "Professional" },
    { value: "friendly", label: "Friendly" },
    { value: "casual", label: "Casual" },
    { value: "formal", label: "Formal" },
    { value: "empathetic", label: "Empathetic" },
  ];

  const generateReply = async () => {
    if (!prompt.trim()) return;

    setLoading(true);

    // Simulate API call delay
    await new Promise((resolve) => setTimeout(resolve, 1500));

    // Replace with your actual AI API call
    const mockReply = `Thank you for reaching out. Based on your message, I understand your concern and would like to help. [This is a ${tone} response generated by AI based on: "${prompt.substring(0, 50)}..."]`;

    setGeneratedReply(mockReply);
    setLoading(false);
  };

  const copyToClipboard = () => {
    navigator.clipboard.writeText(generatedReply);
    alert("Reply copied to clipboard!");
  };

  return (
    <div>
      <h1 className="mb-2 font-bold text-gray-900 text-3xl">
        AI Reply Generator
      </h1>
      <p className="mb-8 text-gray-600">
        Generate intelligent responses with AI assistance
      </p>

      <div className="gap-6 grid grid-cols-1 lg:grid-cols-2">
        {/* Input Section */}
        <div className="bg-white shadow-md p-6 rounded-lg">
          <h2 className="mb-4 font-semibold text-xl">Input</h2>

          <div className="mb-4">
            <label className="block mb-2 font-medium text-gray-700 text-sm">
              Message or Context
            </label>
            <textarea
              value={prompt}
              onChange={(e) => setPrompt(e.target.value)}
              className="px-4 py-3 border border-gray-300 focus:border-transparent rounded-lg focus:ring-2 focus:ring-indigo-500 w-full resize-none"
              rows="8"
              placeholder="Enter the message you want to reply to or provide context..."
            />
          </div>

          <div className="mb-6">
            <label className="block mb-2 font-medium text-gray-700 text-sm">
              Reply Tone
            </label>
            <select
              value={tone}
              onChange={(e) => setTone(e.target.value)}
              className="px-4 py-2 border border-gray-300 focus:border-transparent rounded-lg focus:ring-2 focus:ring-indigo-500 w-full"
            >
              {tones.map((t) => (
                <option key={t.value} value={t.value}>
                  {t.label}
                </option>
              ))}
            </select>
          </div>

          <button
            onClick={generateReply}
            disabled={!prompt.trim() || loading}
            className="flex justify-center items-center bg-indigo-600 hover:bg-indigo-700 disabled:bg-gray-400 px-6 py-3 rounded-lg w-full text-white transition disabled:cursor-not-allowed"
          >
            {loading ? (
              <>
                <svg
                  className="mr-3 -ml-1 w-5 h-5 text-white animate-spin"
                  xmlns="http://www.w3.org/2000/svg"
                  fill="none"
                  viewBox="0 0 24 24"
                >
                  <circle
                    className="opacity-25"
                    cx="12"
                    cy="12"
                    r="10"
                    stroke="currentColor"
                    strokeWidth="4"
                  ></circle>
                  <path
                    className="opacity-75"
                    fill="currentColor"
                    d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"
                  ></path>
                </svg>
                Generating...
              </>
            ) : (
              "Generate Reply"
            )}
          </button>
        </div>

        {/* Output Section */}
        <div className="bg-white shadow-md p-6 rounded-lg">
          <h2 className="mb-4 font-semibold text-xl">Generated Reply</h2>

          {generatedReply ? (
            <div>
              <div className="bg-gray-50 mb-4 p-4 border border-gray-200 rounded-lg min-h-[200px]">
                <p className="text-gray-800 whitespace-pre-wrap">
                  {generatedReply}
                </p>
              </div>

              <div className="flex gap-3">
                <button
                  onClick={copyToClipboard}
                  className="flex-1 bg-green-600 hover:bg-green-700 px-4 py-2 rounded-lg text-white transition"
                >
                  Copy to Clipboard
                </button>
                <button
                  onClick={() => setGeneratedReply("")}
                  className="bg-gray-500 hover:bg-gray-600 px-4 py-2 rounded-lg text-white transition"
                >
                  Clear
                </button>
              </div>

              <div className="bg-blue-50 mt-4 p-3 border border-blue-200 rounded-lg">
                <p className="text-blue-800 text-sm">
                  <strong>Tip:</strong> Review and customize the generated reply
                  before sending to ensure it matches your specific needs.
                </p>
              </div>
            </div>
          ) : (
            <div className="flex justify-center items-center h-[300px] text-gray-400">
              <div className="text-center">
                <svg
                  className="mx-auto mb-4 w-12 h-12"
                  fill="none"
                  stroke="currentColor"
                  viewBox="0 0 24 24"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth="2"
                    d="M8 10h.01M12 10h.01M16 10h.01M9 16H5a2 2 0 01-2-2V6a2 2 0 012-2h14a2 2 0 012 2v8a2 2 0 01-2 2h-5l-5 5v-5z"
                  />
                </svg>
                <p>Your generated reply will appear here</p>
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

export default AIReplyGenerator;
