import passport from 'passport';
import { Strategy as GoogleStrategy } from 'passport-google-oauth20';
import User from '../models/User.model.js';

/**
 * Configure Passport Google OAuth Strategy
 */
export const configurePassport = () => {
  // Google OAuth Strategy
  passport.use(
    new GoogleStrategy(
      {
        clientID: process.env.GOOGLE_CLIENT_ID,
        clientSecret: process.env.GOOGLE_CLIENT_SECRET,
        callbackURL: process.env.GOOGLE_CALLBACK_URL,
        scope: ['profile', 'email'],
      },
      async (accessToken, refreshToken, profile, done) => {
        try {
          console.log('🔐 Google OAuth callback triggered');
          console.log('📧 Google Profile Email:', profile.emails?.[0]?.value);
          console.log('👤 Google Profile Name:', profile.displayName);

          const email = profile.emails?.[0]?.value;
          const googleId = profile.id;

          if (!email) {
            return done(new Error('No email found in Google profile'), null);
          }

          // Check if user already exists
          let user = await User.findOne({
            $or: [
              { email },
              { googleId }
            ]
          });

          if (user) {
            // User exists - update Google info if needed
            console.log('✅ Existing user found:', user.email);

            // Add google to authProviders if not already there
            if (!user.authProviders.includes('google')) {
              user.authProviders.push('google');
            }

            // Update googleId if not set
            if (!user.googleId) {
              user.googleId = googleId;
            }

            // Update email verification status
            if (!user.emailVerified) {
              user.emailVerified = true;
            }

            // Update last login
            user.lastLogin = new Date();

            // Update profile image if not set or using placeholder
            if (!user.image || user.image.includes('placeholder')) {
              user.image = profile.photos?.[0]?.value || user.image;
            }

            await user.save();
            console.log('✅ User updated with Google OAuth info');
            return done(null, user);
          }

          // Create new user
          console.log('🆕 Creating new user from Google OAuth');

          const newUser = await User.create({
            name: profile.displayName,
            email,
            googleId,
            authProviders: ['google'],
            emailVerified: true,
            image: profile.photos?.[0]?.value || 'https://via.placeholder.com/150.jpg',
            lastLogin: new Date()
            // Note: password not required for OAuth users
            // slug will be auto-generated by User model pre-save hook
          });

          console.log('✅ New user created:', newUser.email);
          console.log('🔗 Generated slug:', newUser.slug);
          return done(null, newUser);
        } catch (error) {
          console.error('❌ Google OAuth error:', error);
          return done(error, null);
        }
      }
    )
  );

  // Serialize user for session (we're not using sessions, but required by passport)
  passport.serializeUser((user, done) => {
    done(null, user._id);
  });

  // Deserialize user from session
  passport.deserializeUser(async (id, done) => {
    try {
      const user = await User.findById(id);
      done(null, user);
    } catch (error) {
      done(error, null);
    }
  });
};

export default passport;
